USE EMPLOYEE_DB;

CREATE TABLE DEPARTMENTS(

    DEPARTMENT_ID INT AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR (20),
    PRIMARY KEY (DEPARTMENT_ID)
);


CREATE TABLE ROLES (
    ROLE_ID INT,
    TITLE VARCHAR(25),
    SALARY INT,
    DEPARTMENT_ID INT,
    PRIMARY KEY (ROLE_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID)

);

CREATE TABLE EMPLOYEE (

    EMPLOYEE_ID INT AUTO_INCREMENT,
    FIRST_NAME VARCHAR (30),
    LAST_NAME VARCHAR (30),
    DEPARTMENT_ID INT,
    PRIMARY KEY (EMPLOYEE_ID),
	FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID),
	FOREIGN KEY (DEPARTMENT_ID) REFERENCES ROLES (ROLE_ID)
)
